[package]
name = "ci_perf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-table = "0.4.7"
regex = "1.10.3"
statistical = "1.0.0"
stats-ci = "0.1.0"
